version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: stats.${P_DOMAIN}
    hostname: stats.${P_DOMAIN}
    ports:
      - "19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/data/nedata/cache:/var/cache/netdata
    environment:
      PRIMEHOST_DOMAIN: stats.${P_DOMAIN}
      VIRTUAL_HOST: stats.${P_DOMAIN}
      LETSENCRYPT_HOST: stats.${P_DOMAIN}
      LETSENCRYPT_EMAIL: ${P_MAIL}
      VIRTUAL_PORT: 19999
      PGID: ${P_PGID}
networks:
    default:
       external:
         name: webproxy
